"""Package holding global variables used in application."""

RABBIT = None
WOLF = None
WOLF_IN_GRASS = None
GRASS = None
EMPTY = None

DISTRIBUTION = None

SIMULATION_STEPS = 200

SIMULATION_STOP = False
SIMULATION_PAUSE = False
SIMULATION_RESUME = False
SLEEP_TIME = 0
WAIT_FOR_RESUME = 1

STEP_NO = None
RABBIT_NO = None
GRASS_NO = None
WOLF_NO = None
SIMULATION_STEP = 0

APP = None

LEFT = 0
RIGHT = 1
UP = 2
DOWN = 3

WOLF = 1
RABBIT = 2
GRASS = 3

POSSIBLE = 1
NOT_POSSIBLE = 2

STEPS_ENTRY = None

WOLF_MOVE_COST_ENTRY_MEAN = None
WOLF_MOVE_COST_ENTRY_VARIANCE = None
RABBIT_INIT_ENTRY_MEAN = None
RABBIT_INIT_ENTRY_VARIANCE = None
GRASS_INIT_ENTRY_MEAN = None
GRASS_INIT_ENTRY_VARIANCE = None
WOLF_INIT_ENTRY_MEAN = None
WOLF_INIT_ENTRY_VARIANCE = None
GRASS_ENERGY_ENTRY_MEAN = None
GRASS_ENERGY_ENTRY_VARIANCE = None
BIRTHDAY_WOLF_ENTRY_MEAN = None
BIRTHDAY_WOLF_ENTRY_VARIANCE = None
BIRTHDAY_RABBIT_ENTRY_MEAN = None
BIRTHDAY_RABBIT_ENTRY_VARIANCE = None
WOLF_ENERGY_ENTRY_MEAN = None
WOLF_ENERGY_ENTRY_VARIANCE = None
RABBIT_ENERGY_ENTRY_MEAN = None
RABBIT_ENERGY_ENTRY_VARIANCE = None
RABBIT_MOVE_COST_ENTRY_MEAN = None
RABBIT_MOVE_COST_ENTRY_VARIANCE = None
